---
output: 
  pdf_document:
    fig_caption: yes
geometry: margin=1in
classoption: letterpaper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, results = "hide", fig.show = "hide")
```

## Appendix: R codes

## Data Cleaning

```{r, results = "hide"}
sUrl = "http://www.bristol.ac.uk/cmm/media/migrated/jsp.zip"
dir.create(file.path("..", "data"), showWarnings = FALSE)
(Pmisc::downloadIfOld(sUrl, file.path("..", "data")))
```


```{r}
school = read.fwf("../data/JSP.DAT", widths = c(2,
1, 1, 1, 2, 4, 2, 2, 1), col.names = c("school",
"class", "gender", "socialClass", "ravensTest",
"student", "english", "math", "year"))
school$socialClass = factor(school$socialClass, labels = c("I",
"II", "IIIn", "IIIm", "IV", "V", "longUnemp", "currUnemp",
"absent"))
school$gender = factor(school$gender, labels = c("f",
"m"))
school$classUnique = paste(school$school, school$class)
school$studentUnique = paste(school$school, school$class,
school$student)
school$grade = factor(school$year)
# (40 - school$math) is the number of questions students get wrong
school$numWrong = 40 -school$math
par( mar=c(4, 1.8, 1, 1))
```

### Distribution of y

```{r, fig.height=3, fig.cap="Histogram of the number of questions students get wrong"}
hist(40 - school$math, breaks = 100, xlab=NULL, main = NULL)
```

### Model

```{r}
library(INLA)
model = inla(numWrong ~ gender + socialClass + grade 
             + f(school, model = "iid", prior = 'pc.prec', param = c(0.2, 0.5)) 
             + f(classUnique, model = "iid", prior = 'pc.prec', param = c(0.2, 0.5))
             + f(studentUnique, model = "iid", prior = 'pc.prec', param = c(0.2, 0.5)), 
             family = "poisson", data = school, 
             control.fixed = list(mean = 0, mean.intercept = 0, 
                                  prec = (0.2)^(-2), prec.intercept = (10)^(-2)))
sdRes = Pmisc::priorPostSd(model)
```

### Tables of Posterior Quantitles

```{r}
knitr::kable(model$summary.fixed[, c(4, 3, 5)], digits = 3, 
             caption = "Posterior quantiles of the fixed effects", 
             label = 'tab:atable')
```


```{r}
knitr::kable(sdRes$summary[, c(4, 3, 5)], digits = 3, 
             caption = "Posterior quantiles of the random effects", 
             label = 'tab:atable')
```

### Plots of posterior distributions comparing to prior distributions

```{r, fig.cap="Priors and Posteriors for fixed effects", fig.height = 4.5}
par(mfrow = c(3, 4), mar=c(4, 1.8, 1, 1))
plot(model$marginals.fixed$'(Intercept)', type='l', col="blue", xlab = "intercept")
xseq = model$marginals.fixed$'(Intercept)'[,'x']
lines(xseq, dnorm(xseq, mean = 0, sd = 10), type="l", col="red")
legend("topright", lty = 1, col = c("blue","red"), legend = c("post","prior"))
for (D in rownames(model$summary.fixed)[2:length(rownames(model$summary.fixed))]){
  plot(model$marginals.fixed[[D]], type = "l", col="blue", xlab = D)
  xseq= model$marginals.fixed[[D]][,'x']
  lines(xseq, dnorm(xseq, sd=0.2), type = "l", col="red")
  legend("topright", lty = 1, col = c("blue","red"), legend = c("post","prior"))
}
```

```{r, fig.cap="Priors and Posteriors for SD of random effects",fig.height=1.5}
par(mfrow = c(1, 3), mar=c(4, 1, 1, 1))
sdRes$school$matplot$xlab = "SD of school"
do.call(matplot, sdRes$school$matplot)
do.call(legend, sdRes$legend)
sdRes$classUnique$matplot$xlab = "SD of classUnique"
do.call(matplot, sdRes$classUnique$matplot)
do.call(legend, sdRes$legend)
sdRes$studentUnique$matplot$xlab = "SD of studentUnique"
do.call(matplot, sdRes$studentUnique$matplot)
do.call(legend, sdRes$legend)
```



